// Legal Database of Uzbekistan Legislation
// Source: Verified LexUZ database

export const LEGAL_DOCUMENTS = [
  {
    id: 'konstitutsiya',
    title: 'O‘zbekiston Respublikasi Konstitutsiyasi',
    articleCount: 128,
    icon: 'document-blue',
    iconColor: '#1976F3',
    iconBg: '#EAF3FF',
    docNumber: 'O‘RQ-828',
    adoptionDate: '2023-04-30',
    effectiveDate: '2023-05-01',
    lexUrl: 'https://lex.uz/docs/6445145'
  },
  {
    id: 'jinoyat-kodeksi',
    title: 'Jinoyat kodeksi',
    articleCount: 486,
    icon: 'document-red',
    iconColor: '#D93025',
    iconBg: '#FEEFEF',
    docNumber: '757-XII',
    adoptionDate: '1994-09-22',
    effectiveDate: '1995-04-01',
    lexUrl: 'https://lex.uz/docs/111453'
  },
  {
    id: 'mamuriy-kodeks',
    title: 'Ma’muriy javobgarlik to‘g‘risidagi kodeks',
    articleCount: 432,
    icon: 'document-blue',
    iconColor: '#1976F3',
    iconBg: '#EAF3FF',
    docNumber: '2015-XII',
    adoptionDate: '1994-09-22',
    effectiveDate: '1995-04-01',
    lexUrl: 'https://lex.uz/docs/97664'
  },
  {
    id: 'fuqarolik-kodeksi',
    title: 'Fuqarolik kodeksi',
    articleCount: 766,
    icon: 'document-purple',
    iconColor: '#7B1FA2',
    iconBg: '#F3E5F5',
    docNumber: '163-I / 256-I',
    adoptionDate: '1996-08-29',
    effectiveDate: '1997-03-01',
    lexUrl: 'https://lex.uz/docs/111189'
  },
  {
    id: 'mehnat-kodeksi',
    title: 'Mehnat kodeksi',
    articleCount: 274,
    icon: 'document-indigo',
    iconColor: '#3F51B5',
    iconBg: '#E8EAF6',
    docNumber: 'O‘RQ-798',
    adoptionDate: '2022-10-28',
    effectiveDate: '2023-04-30',
    lexUrl: 'https://lex.uz/docs/6257288'
  },
  {
    id: 'axborot-qonun',
    title: 'Axborot erkinligi to‘g‘risidagi qonun',
    articleCount: 19,
    icon: 'document-orange',
    iconColor: '#F57C00',
    iconBg: '#FFF3E0',
    docNumber: '439-II',
    adoptionDate: '2002-12-12',
    effectiveDate: '2003-01-15',
    lexUrl: 'https://lex.uz/docs/51950'
  }
];

export const LEGAL_ARTICLES = [
  {
    id: 'mjt-183',
    documentId: 'mamuriy-kodeks',
    documentTitle: 'Ma’muriy javobgarlik to‘g‘risidagi kodeks',
    articleNumber: 'Modda 183',
    title: 'Axborot sohasidagi huquqbuzarliklar',
    content: 'Axborotning tarqatilishi tartibini buzish, shuningdek, internet tarmoq’ida qonun hujjatlarida taqiqlangan axborotlarni tarqatish — ma’muriy javobgarlikka sabab bo‘ladi.',
    penaltyText: 'BHMning 3 baravaridan 5 baravarigacha jarima yoki 15 sutkagacha ma’muriy qamoq jazosi qo‘llaniladi.',
    docNumber: 'O‘RQ-472',
    adoptionDate: '2021-10-12',
    effectiveDate: '2022-01-01',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/97664#183',
    keywords: ['internet', 'axborot', 'tarmoq', 'tarqatish', 'post', 'kontent', 'taqiqlangan', 'haqorat']
  },
  {
    id: 'mjt-41',
    documentId: 'mamuriy-kodeks',
    documentTitle: 'Ma’muriy javobgarlik to‘g‘risidagi kodeks',
    articleNumber: 'Modda 41',
    title: 'Haqorat qilish',
    content: 'Fuqaroning sha’ni va qadr-qimmatini beodoblik bilan qasddan tahqirlash — ma’muriy javobgarlikka va belgilangan tartibda jarima solishga sabab bo‘ladi.',
    penaltyText: 'BHMning 20 baravaridan 40 baravarigacha miqdorda jarima solishga sabab bo‘ladi (MJtK 41-modda).',
    docNumber: '2015-XII',
    adoptionDate: '1994-09-22',
    effectiveDate: '1995-04-01',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/97664#41',
    keywords: ['haqorat', 'haqoratlash', 'so\'kish', 'tahqirlash', 'qadr-qimmat', 'haqorat qilaman']
  },
  {
    id: 'mjt-40',
    documentId: 'mamuriy-kodeks',
    documentTitle: 'Ma’muriy javobgarlik to‘g‘risidagi kodeks',
    articleNumber: 'Modda 40',
    title: 'Tuhmat',
    content: 'Tuhmat, ya’ni bilib turib boshqa shaxsni sharmanda qiladigan uydirmalar tarqatish — ma’muriy javobgarlikka sabab bo‘ladi.',
    penaltyText: 'BHMning 20 baravaridan 60 baravarigacha miqdorda jarima solishga sabab bo‘ladi (MJtK 40-modda).',
    docNumber: '2015-XII',
    adoptionDate: '1994-09-22',
    effectiveDate: '1995-04-01',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/97664#40',
    keywords: ['tuhmat', 'sharmanda', 'uydirma', 'yolg\'on', 'bo\'hton']
  },
  {
    id: 'jk-140',
    documentId: 'jinoyat-kodeksi',
    documentTitle: 'Jinoyat kodeksi',
    articleNumber: 'Modda 140',
    title: 'Haqorat qilish',
    content: 'Haqorat qilish, ya’ni shaxsning sha’ni va qadr-qimmatini beodoblik bilan qasddan tahqirlash, shunday harakatlar uchun ma’muriy jazo qo‘llanilganidan keyin sodir etilgan bo‘lsa — jinoiy javobgarlikka sabab bo‘ladi.',
    penaltyText: 'BHMning 200 baravarigacha jarima yoki 1 yilgacha axloq tuzatish ishlari (Jinoiy javobgarlik!).',
    docNumber: '757-XII',
    adoptionDate: '1994-09-22',
    effectiveDate: '1995-04-01',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/111453#140',
    keywords: ['haqorat', 'jinoyat', 'tahqirlash', 'beodoblik']
  },
  {
    id: 'jk-205',
    documentId: 'jinoyat-kodeksi',
    documentTitle: 'Jinoyat kodeksi',
    articleNumber: 'Modda 205',
    title: 'Tarmoqlar orqali tarqatish',
    content: 'Axborot-telekommunikatsiya tarmoqlaridan foydalangan holda taqiqlangan axborot resurslarini tarqatish yoki targ‘ib qilish javobgarlikka sabab bo‘ladi.',
    docNumber: '757-XII',
    adoptionDate: '1994-09-22',
    effectiveDate: '1995-04-01',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/111453#205',
    keywords: ['tarmoqlar', 'tarqatish', 'internet', 'mansab', 'resurs']
  },
  {
    id: 'axborot-6',
    documentId: 'axborot-qonun',
    documentTitle: 'Axborot erkinligi to‘g‘risidagi qonun',
    articleNumber: 'Modda 6',
    title: 'Internet tarmoq’idan foydalanish',
    content: 'Internet tarmoq’idan foydalanishda fuqarolar va tashkilotlarning huquqlari hamda qonuniy manfaatlari O‘zbekiston Respublikasi qonunlariga muvofiq himoya qilinadi.',
    docNumber: '439-II',
    adoptionDate: '2002-12-12',
    effectiveDate: '2003-01-15',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/51950#6',
    keywords: ['internet', 'erkinlik', 'foydalanish', 'huquq', 'manfaat']
  },
  {
    id: 'konst-27',
    documentId: 'konstitutsiya',
    documentTitle: 'O‘zbekiston Respublikasining Konstitutsiyasi',
    articleNumber: 'Modda 27',
    title: 'Axborot izlash va tarqatish huquqi',
    content: 'Har bir inson axborot erkinligiga haqlidir. Har kim axborotni izlash, olish va tarqatish huquqiga ega, davlat siri va qonun bilan qo‘riqlanadigan boshqa sirlarga daxldor axborotlar bundan mustasno.',
    docNumber: 'O‘RQ-828',
    adoptionDate: '2023-04-30',
    effectiveDate: '2023-05-01',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/6445145#27',
    keywords: ['konstitutsiya', 'axborot', 'erkinlik', 'tarqatish', 'huquq']
  },
  {
    id: 'mehnat-161',
    documentId: 'mehnat-kodeksi',
    documentTitle: 'Mehnat kodeksi',
    articleNumber: 'Modda 161',
    title: 'Mehnat shartnomasini bekor qilish',
    content: 'Mehnat shartnomasi xodimning tashabbusi yoki ish beruvchining tashabbusi bilan qonuniy asoslarda bekor qilinishi mumkin.',
    docNumber: 'O‘RQ-798',
    adoptionDate: '2022-10-28',
    effectiveDate: '2023-04-30',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/6257288#161',
    keywords: ['mehnat', 'shartnoma', 'ish', 'bekor qilish', 'xodim']
  },
  {
    id: 'fuqarolik-99',
    documentId: 'fuqarolik-kodeksi',
    documentTitle: 'Fuqarolik kodeksi',
    articleNumber: 'Modda 99',
    title: 'Sha’n, qadr-qimmat va ishchanlik obro‘sini himoya qilish',
    content: 'Fuqaro o‘z sha’ni, qadr-qimmati yoki ishchanlik obro‘siga putur yetkazuvchi ma’lumotlar yuzasidan raddiya talab qilish huquqiga ega.',
    docNumber: '163-I',
    adoptionDate: '1996-08-29',
    effectiveDate: '1997-03-01',
    source: 'LexUZ',
    lexUrl: 'https://lex.uz/docs/111189#99',
    keywords: ['fuqarolik', 'sha\'n', 'obro\'', 'raddiya', 'himoya']
  }
];
